---
extends: "default"

ignore:
  - '*/node_modules/'
  - '*/target/'


rules:
  # 80 chars should be enough, but don't fail if a line is longer
  line-length:
    max: 160
    level: "warning"

  quoted-strings:
    quote-type: "any"
    required: true
    allow-quoted-quotes: false
    check-keys: false
