const COUNTRIES = [
    {value: "Afghanistan", label_en: "Afghanistan", label_nl: "Afghanistan"},
    {value: "Albania", label_en: "Albania", label_nl: "Albanië"},
    {value: "Algeria", label_en: "Algeria", label_nl: "Algerije"},
    {value: "Argentina", label_en: "Argentina", label_nl: "Argentinië"},
    {value: "Australia", label_en: "Australia", label_nl: "Australië"},
    {value: "Austria", label_en: "Austria", label_nl: "Oostenrijk"},
    {value: "Belgium", label_en: "Belgium", label_nl: "België"},
    {value: "Brazil", label_en: "Brazil", label_nl: "Brazilië"},
    {value: "Bulgaria", label_en: "Bulgaria", label_nl: "Bulgarije"},
    {value: "Canada", label_en: "Canada", label_nl: "Canada"},
    {value: "Chile", label_en: "Chile", label_nl: "Chili"},
    {value: "China", label_en: "China", label_nl: "China"},
    {value: "Colombia", label_en: "Colombia", label_nl: "Colombia"},
    {value: "Croatia", label_en: "Croatia", label_nl: "Kroatië"},
    {value: "Cyprus", label_en: "Cyprus", label_nl: "Cyprus"},
    {value: "Czech Republic", label_en: "Czech Republic", label_nl: "Tsjechië"},
    {value: "Denmark", label_en: "Denmark", label_nl: "Denemarken"},
    {value: "Egypt", label_en: "Egypt", label_nl: "Egypte"},
    {value: "Estonia", label_en: "Estonia", label_nl: "Estland"},
    {value: "Finland", label_en: "Finland", label_nl: "Finland"},
    {value: "France", label_en: "France", label_nl: "Frankrijk"},
    {value: "Germany", label_en: "Germany", label_nl: "Duitsland"},
    {value: "Greece", label_en: "Greece", label_nl: "Griekenland"},
    {value: "Hungary", label_en: "Hungary", label_nl: "Hongarije"},
    {value: "Iceland", label_en: "Iceland", label_nl: "IJsland"},
    {value: "India", label_en: "India", label_nl: "India"},
    {value: "Indonesia", label_en: "Indonesia", label_nl: "Indonesië"},
    {value: "Ireland", label_en: "Ireland", label_nl: "Ierland"},
    {value: "Israel", label_en: "Israel", label_nl: "Israël"},
    {value: "Italy", label_en: "Italy", label_nl: "Italië"},
    {value: "Japan", label_en: "Japan", label_nl: "Japan"},
    {value: "Latvia", label_en: "Latvia", label_nl: "Letland"},
    {value: "Lithuania", label_en: "Lithuania", label_nl: "Litouwen"},
    {value: "Luxembourg", label_en: "Luxembourg", label_nl: "Luxemburg"},
    {value: "Malta", label_en: "Malta", label_nl: "Malta"},
    {value: "Mexico", label_en: "Mexico", label_nl: "Mexico"},
    {value: "Morocco", label_en: "Morocco", label_nl: "Marokko"},
    {value: "Netherlands", label_en: "Netherlands", label_nl: "Nederland"},
    {value: "New Zealand", label_en: "New Zealand", label_nl: "Nieuw-Zeeland"},
    {value: "Norway", label_en: "Norway", label_nl: "Noorwegen"},
    {value: "Poland", label_en: "Poland", label_nl: "Polen"},
    {value: "Portugal", label_en: "Portugal", label_nl: "Portugal"},
    {value: "Romania", label_en: "Romania", label_nl: "Roemenië"},
    {value: "Russia", label_en: "Russia", label_nl: "Rusland"},
    {value: "Saudi Arabia", label_en: "Saudi Arabia", label_nl: "Saoedi-Arabië"},
    {value: "Serbia", label_en: "Serbia", label_nl: "Servië"},
    {value: "Singapore", label_en: "Singapore", label_nl: "Singapore"},
    {value: "Slovakia", label_en: "Slovakia", label_nl: "Slowakije"},
    {value: "Slovenia", label_en: "Slovenia", label_nl: "Slovenië"},
    {value: "South Africa", label_en: "South Africa", label_nl: "Zuid-Afrika"},
    {value: "South Korea", label_en: "South Korea", label_nl: "Zuid-Korea"},
    {value: "Spain", label_en: "Spain", label_nl: "Spanje"},
    {value: "Sweden", label_en: "Sweden", label_nl: "Zweden"},
    {value: "Switzerland", label_en: "Switzerland", label_nl: "Zwitserland"},
    {value: "Taiwan", label_en: "Taiwan", label_nl: "Taiwan"},
    {value: "Turkey", label_en: "Turkey", label_nl: "Turkije"},
    {value: "Ukraine", label_en: "Ukraine", label_nl: "Oekraïne"},
    {value: "United Arab Emirates", label_en: "United Arab Emirates", label_nl: "Verenigde Arabische Emiraten"},
    {value: "United Kingdom", label_en: "United Kingdom", label_nl: "Verenigd Koninkrijk"},
    {value: "United States", label_en: "United States", label_nl: "Verenigde Staten"},
];

export function countryOptions(locale) {
    return COUNTRIES.map(c => ({
        value: c.value,
        label: locale === "nl" ? c.label_nl : c.label_en,
    }));
}

export default COUNTRIES;
