package access.invite;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.ResponseEntity;
import org.springframework.http.client.support.BasicAuthenticationInterceptor;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import java.util.List;
import java.util.Map;

@Service
public class InviteClient {

    private final String baseUrl;
    private final String manageIdentifier;
    private final String manageType;
    private final String clientUrl;
    private final RestTemplate restTemplate;

    public InviteClient(@Value("${invite.base-url}") String baseUrl,
                        @Value("${invite.manage-identifier}") String manageIdentifier,
                        @Value("${invite.manage-type}") String manageType,
                        @Value("${config.client-url}") String clientUrl,
                        @Value("${invite.user}") String userName,
                        @Value("${invite.password}") String password) {
        this.baseUrl = this.removeTrailingSlash(baseUrl);
        this.manageIdentifier = manageIdentifier;
        this.manageType = manageType;
        this.clientUrl = this.removeTrailingSlash(clientUrl);
        this.restTemplate = new RestTemplate();
        this.restTemplate.getInterceptors().add(new BasicAuthenticationInterceptor(userName, password));
    }

    @SuppressWarnings("unchecked")
    public Map<String, Object> createRole(String name) {
        ResponseEntity<Map> responseEntity = restTemplate.postForEntity(
                String.format("%s/api/external/v1/internal/invite/roles", baseUrl),
                roleTemplate(name),
                Map.class);
        return responseEntity.getBody();
    }

    private Map<String, Object> roleTemplate(String name) {
        return Map.of(
                "name", name,
                "shortName", name,
                "description", "Autogenerated Role for Access",
                "defaultExpiryDays", 5 * 365,
                "inviterDisplayName", "Access",
                "applicationUsages", List.of(
                        Map.of(
                                "landingPage", String.format("%s/organizations", clientUrl),
                                "application", Map.of(
                                        "manageId", manageIdentifier,
                                        "manageType", manageType
                                )
                        )
                )
        );
    }

    private String removeTrailingSlash(String baseUrl) {
        if (baseUrl.endsWith("/")) {
            return baseUrl.substring(0, baseUrl.length() - 1);
        }
        return baseUrl;
    }
}
